version: '3.9'

services: 
  db:
    image: postgres:11
    env_file: 
      - .env/development/database
    volumes: 
      - dbdata:/var/lib/postgresql/data/pgdata
  
  web:
    build: .
    ports: 
      - '3000:3000'
      - '4000:4000'
    env_file: 
      - .env/development/database
      - .env/development/web
      - .env/development/browser
    volumes: 
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on: 
      - db
      - chrome

  guard:
    build: .
    env_file: 
      - .env/development/web
      - .env/development/database
    volumes: 
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on: 
      - db
    command: bundle exec guard --no-bundler-warning --no-interactions
  
  chrome:
    image: selenium/standalone-chrome:93.0
    volumes:
      - /dev/shm:/dev/shm

  redis:
    image: redis
    
volumes: 
  gem_cache:
  dbdata:
    external:
      name: my_db_data
      