version: '3.9'

services: 
  db:
    image: postgres:11
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    volumes: 
      - dbdata:/var/lib/postgresql/data/pgdata
  
  web:
    build: .
    ports: 
      - '3000:3000'
    environment: 
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
      - HUB_URL=http://chrome:4444
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - db
      - chrome

  guard:
    build: .
    environment: 
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - db
    command: bundle exec guard --no-bundler-warning --no-interactions
  
  chrome:
    image: selenium/standalone-chrome:93.0
    volumes:
      - /dev/shm:/dev/shm

volumes: 
  dbdata:
    external:
      name: my_db_data
      